modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/ItemStages"
license="LGPL v2.1"

[[mods]]
modId="itemstages"
updateJSONURL="https://updates.blamejared.com/get?n=itemstages&gv=1.16.5"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:clock"

[[dependencies.itemstages]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemstages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemstages]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.itemstages]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[7.1,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.itemstages]]
    modId="gamestages"
    mandatory=false
    versionRange="[7.3,)"
    ordering="AFTER"
    side="BOTH"