modLoader="javafml"
loaderVersion="[43,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/ItemStages"
license="LGPL v2.1"

[[mods]]
modId="itemstages"
#updateJSONURL="https://updates.blamejared.com/get?n=itemstages&gv=1.19.2"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:clock"

[[dependencies.itemstages]]
    modId="forge"
    mandatory=true
    versionRange="[43,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemstages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemstages]]
    modId="bookshelf"
    mandatory=true
    versionRange="[16,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.itemstages]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.itemstages]]
    modId="gamestages"
    mandatory=false
    versionRange="[11,)"
    ordering="AFTER"
    side="BOTH"