modLoader="javafml"
loaderVersion="[47,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/ItemStages"
license="LGPL v2.1"

[[mods]]
modId="itemstages"
#updateJSONURL="https://updates.blamejared.com/get?n=itemstages&gv=1.20"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:clock"

[[dependencies.itemstages]]
    modId="forge"
    mandatory=true
    versionRange="[47,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemstages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemstages]]
    modId="bookshelf"
    mandatory=true
    versionRange="[20,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.itemstages]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[14,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.itemstages]]
    modId="gamestages"
    mandatory=false
    versionRange="[15,)"
    ordering="AFTER"
    side="BOTH"